include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    must_be_immutable: ignore
    sdk_version_since: ignore
    type_literal_in_constant_pattern: ignore
    use_build_context_synchronously: ignore
    unused_field: ignore
    unused_local_variable: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    prefer_typing_uninitialized_variables: ignore

linter:
  rules:
    #    use_string_in_part_of_directives: ignore
    #    avoid_print: false
    prefer_single_quotes: true
#    sort_constructors_first: false
    always_specify_types: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: true
    sort_constructors_first: false
