import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:responsive_builder/responsive_builder.dart';
import '../../../../../core/shared/widgets/custom_back_icon.dart' show CustomBackIcon;
import '../../../../../core/utils/constant/app_constant.dart';
import '../../../../../core/utils/constant/app_strings.dart' show AppStrings;
import '../../../../../core/utils/extensions/extensions.dart';
import '../../../../../core/utils/validations/validator.dart';
import '../../../../../core/utils/widgets/form_fields/default_password_form_field.dart';
import '../../../../../core/utils/widgets/misc/custom_scaffold_widget.dart';
import '../../../shared/auth_header_content.dart' show AuthHeaderContent;
import '../../../shared/auth_subtitle_text.dart';
import '../../../shared/auth_title_widget.dart';
import '../../../shared/auth_title_bold_text.dart';
import '../../data/params/reset_password_route_params.dart';
import '../../logic/reset_password_cubit.dart';
import '../../logic/reset_password_state.dart';
import 'reset_password_button_widget.dart';
part '../pages/reset_password_screen.dart';
part '../pages/reset_password_screen_mobile_design.dart';
