// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzwmRFXJ43LwaJnH4zjqL7da_NzyJlZ4',
    appId: '1:40769922379:android:0c3ea9f2b7e51ebc7db4ce',
    messagingSenderId: '40769922379',
    projectId: 'bait-alasgadia',
    storageBucket: 'bait-alasgadia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD80WfN-Md6D3eajkAUYyt0BUJZ4rWaysk',
    appId: '1:40769922379:ios:3e965be5a77024027db4ce',
    messagingSenderId: '40769922379',
    projectId: 'bait-alasgadia',
    storageBucket: 'bait-alasgadia.firebasestorage.app',
    iosBundleId: 'com.innova.mazaadat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzrNytwngebuSkDLtXIJB6gnZIHix3RrE',
    appId: '1:40769922379:web:604d53902a81a8c57db4ce',
    messagingSenderId: '40769922379',
    projectId: 'bait-alasgadia',
    authDomain: 'bait-alasgadia.firebaseapp.com',
    storageBucket: 'bait-alasgadia.firebasestorage.app',
    measurementId: 'G-EDX2ZWFMNW',
  );

}